# This is the MOST important setting for your custom domain
baseURL = "https://familie-schule-betreuung.ch/"

languageCode = "en-us"
title = "Familie, Schule & Betreuung"

# This tells Hugo to use the theme you just added
theme = "mainroad"

# You can add more theme-specific settings here.
# For example, to add a description:
[Params]
  description = "Familie, Schule & Betreuung - Hand in Hand"


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Standpunkte"
  url = "/standpunkte/"
  weight = 30

[[menu.main]]
  name = "Ãœber uns"
  url = "/about_us/"
  weight = 40


  [[menu.main]]
  name = "Beitreten"
  url = "/beitreten/"
  weight = 40